### ISSUE TITLE
Seeder Path Directory Creation

### ISSUE THREAD

**Issue by ssiva13** [AntonyZ89/yii2-seeder#3]
Creates the directory specified as $seederPath without reading the alias. **_@app/seeder_**

Please change **_SeederController.php_** line 267

From 
```
FileHelper::createDirectory($this->seederPath);
```

to 

```
FileHelper::createDirectory(Yii::getAlias($this->seederPath));
```

**Comment by AntonyZ89** [comment]
@ssiva13 done

**Comment by ssiva13** [comment]
Thanks!!
